### ISSUE TITLE
Not working with new RTEMS release

### ISSUE THREAD

**Issue by NicolaGiardino** [rmspacefish/rtems-lwip#2]
The latest RTEMS version has the HALs for the Nucleo H743 updated to the v1.11.1. 
This version changes a lot from the previous ones, and so the project doesn't work anymore. I've tried going back to the previous ethernet drivers but the LAN drivers stay in link down. With the newest, I've tried copying what ST does in its example projects, but this results in a memory exception inside `netif_set_link_up`, here the backtrace from GDB:

```
#0  0x08000ff4 in mem_malloc ()
#1  0x08002ab4 in pbuf_alloc ()
#2  0x08009b8e in etharp_raw ()
#3  0x08009c84 in etharp_request_dst ()
#4  0x08009ca8 in etharp_request ()
#5  0x0800625a in netif_issue_reports ()
#6  0x080062e8 in netif_set_link_up ()
#7  0x0800f148 in low_level_init ()
#8  0x0800ef4e in ethernetif_init ()
#9  0x08005e3a in netif_add ()
#10 0x0800e8aa in rtems_lwip_init ()
```

**Comment by robamu** [comment]
Hmm it should work with the older drivers. Unfortunately, I have not done anything with RTEMS and the STM32 in a long time. I might give it another try soon. Which H743 are you using specifically? There is a separate BSP for the H743 if I remember correctly. Which BSP are you using?

**Comment by NicolaGiardino** [comment]
I'm using the Nucleo H743ZI2, with the latest BSPs. Unfortunately in the latest version of RTEMS the BSPs were updated to v1.11.1, so I tried updating yout project too, resulting in this strange behaviour. The strange thing is that the variables being allocated are exactly the same as before, nothing's changed in this version. If you want I can give you all the source

**Comment by robamu** [comment]
The special thing about lwIP was the allocation of memory segments for lwIP. If I remember correctly, that was done using special preprocessor segments which were sometimes different depending on the architecture. Maybe something in the HALs were changed that this needs adaption, but I have not had a chance to look at it yet.
